// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace IndexModuleCssNamespace {
    export interface IIndexModuleCss {
        angle_position_both: string;
        angle_position_bottom: string;
        angle_position_top: string;
        angle_section: string;
        guides_guid: string;
    }
}

declare const IndexModuleCssModule: IndexModuleCssNamespace.IIndexModuleCss;

export = IndexModuleCssModule;
